In [27]:
# Please refer to the “Purchase Data” worksheet of Lab Session Data.xlsx. Please load the data and segregate them into 2 matrices X & y (following the nomenclature of Xc = y). Do the following activities. X : matrix containing all observation/feature vectors and y is the vector containing all output values. Features Columns are: (i) Candies (#), (ii) Mangoes (Kg), and (iii) Milk Packets (#); Output data is available in “Payment (Rs)” column. 
import pandas as pd
import numpy as np
def load_purchase_data(file_name):
    dataframe = pd.read_excel(file_name, sheet_name="Purchase data")
    return dataframe
def create_feature_matrix(dataframe):
    feature_matrix = dataframe[["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].to_numpy()
    return feature_matrix
def create_output_vector(dataframe):
    output_vector = dataframe["Payment (Rs)"].to_numpy()
    return output_vector
def calculate_rank(feature_matrix):
    rank = np.linalg.matrix_rank(feature_matrix)
    return rank
def calculate_product_cost(feature_matrix, output_vector):
    pseudo_inverse = np.linalg.pinv(feature_matrix)
    product_cost = pseudo_inverse @ output_vector
    return product_cost
purchase_data = load_purchase_data("Lab Session Data.xlsx")
X = create_feature_matrix(purchase_data)
y = create_output_vector(purchase_data)
rank = calculate_rank(X)
product_cost = calculate_product_cost(X, y)
print("Feature Matrix (X) : ")
print(X)
print("Output Vector (y) : ")
print(y)
print("Dimensionality of Vector Space : ", X.shape[1])
print("Number of Vectors              : ", X.shape[0])
print("Rank of Feature Matrix : ", rank)
print("Cost of Products       : " , product_cost)
print("Candy : ", product_cost[0])
print("Mango : ", product_cost[1])
print("Milk  : ", product_cost[2])

Feature Matrix (X) : 
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Output Vector (y) : 
[386 289 393 110 280 167 271 274 148 198]
Dimensionality of Vector Space :  3
Number of Vectors              :  10
Rank of Feature Matrix :  3
Cost of Products       :  [ 1. 55. 18.]
Candy :  1.000000000000015
Mango :  54.99999999999999
Milk  :  17.999999999999996


In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
def calculate_stock_data(file_name):
    dataframe=pd.read_excel(file_name,sheet_name="IRCTC Stock Price")
    return dataframe
def numpy_mean(price_data):
    return np.mean(price_data)

def numpy_variance(price_data):
    return np.var(price_data)

def calculate_mean(price_data):
    total=0
    count=0
    for value in price_data:
        total+=value
        count+=1
    return total/count
def calculate_variance(price_data):
    mean=calculate_mean(price_data)
    total=0
    count=len(price_data)
    for value in price_data:
        total+=(value-mean)**2
    return total/count
def execution_time(function_name,data):
    total_time=0
    for i in range(10):
        start_time=time.perf_counter()
        function_name(data)
        end_time=time.perf_counter()
        total_time+=(end_time-start_time)
    return total_time/10
def wednesday_mean(dataframe):
    wednesday_price=dataframe[dataframe["Day"]=="Wednesday"]["Price"]
    return np.mean(wednesday_price)
def april_mean(dataframe):
    april_price=dataframe[dataframe["Month"]=="Apr"]["Price"]
    return np.mean(april_price)
def probability_of_loss(dataframe):
    loss=dataframe["Chg%"].apply(lambda value:value<0)
    return loss.sum()/len(dataframe)
def probability_of_profit_on_wednesday(dataframe):
    wednesday=dataframe[dataframe["Day"]=="Wednesday"]
    profit=wednesday["Chg%"].apply(lambda value:value>0)
    return profit.sum()/len(wednesday)
def conditional_probability(dataframe):
    wednesday=dataframe[dataframe["Day"]=="Wednesday"]
    profit=wednesday[wednesday["Chg%"]>0]
    return len(profit)/len(wednesday)
def scatter_plot(dataframe):
    plt.figure(figsize=(8,5))
    plt.scatter(dataframe["Day"],dataframe["Chg%"])
    plt.title("Day vs Chg%")
    plt.xlabel("Day")
    plt.ylabel("Chg%")
    plt.grid(True)
    plt.show()
stock_data=calculate_stock_data("Lab Session Data.xlsx")
price=stock_data["Price"]
numpy_mean_value=numpy_mean(price)
numpy_variance_value=numpy_variance(price)
manual_mean=calculate_mean(price)
manual_variance=calculate_variance(price)
numpy_mean_time=execution_time(numpy_mean,price)
manual_mean_time=execution_time(calculate_mean,price)
numpy_variance_time=execution_time(numpy_variance,price)
manual_variance_time=execution_time(calculate_variance,price)
wednesday_average=wednesday_mean(stock_data)
april_average=april_mean(stock_data)
loss_probability=probability_of_loss(stock_data)
profit_probability=probability_of_profit_on_wednesday(stock_data)
conditional_profit=conditional_probability(stock_data)
print("Mean using NumPy :",numpy_mean_value)
print("Variance using NumPy :",numpy_variance_value)
print()
print("Mean using Manual Function :",manual_mean)
print("Variance using Manual Function :",manual_variance)
print()
print("Average Execution Time (NumPy Mean):",numpy_mean_time)
print("Average Execution Time (Manual Mean):",manual_mean_time)
print()
print("Average Execution Time (NumPy Variance):",numpy_variance_time)
print("Average Execution Time (Manual Variance):",manual_variance_time)
print()
print("Mean Price on Wednesdays :",wednesday_average)
print("Mean Price in April :",april_average)
print()
print("Probability of Loss :",loss_probability)
print("Probability of Profit on Wednesday :",profit_probability)
print("Conditional Probability of Profit given Wednesday :",conditional_profit)

scatter_plot(stock_data)

C:\Users\jaswa\AppData\Local\Temp\ipykernel_2700\2308054921.py:56: RuntimeWarning: invalid value encountered in scalar divide
  return profit.sum()/len(wednesday)


ZeroDivisionError: division by zero

In [19]:
import pandas as pd
import numpy as np
def calculate_thyroid_data(file_name):
    dataframe=pd.read_excel(file_name,sheet_name="thyroid0387_UCI")
    return dataframe
def attribute_datatype(dataframe):
    return dataframe.dtypes
def categorical_attributes(dataframe):
    return dataframe.select_dtypes(include=["object"]).columns
def numerical_attributes(dataframe):
    return dataframe.select_dtypes(include=[np.number]).columns
def data_range(dataframe):
    return dataframe.describe()
def missing_values(dataframe):
    return dataframe.isnull().sum()
def outliers(dataframe):
    numerical=dataframe.select_dtypes(include=[np.number])
    Q1=numerical.quantile(0.25)
    Q3=numerical.quantile(0.75)
    IQR=Q3-Q1
    outlier=((numerical<(Q1-1.5*IQR))|(numerical>(Q3+1.5*IQR))).sum()
    return outlier
def mean_value(dataframe):
    numerical=dataframe.select_dtypes(include=[np.number])
    return numerical.mean()
def variance_value(dataframe):
    numerical=dataframe.select_dtypes(include=[np.number])
    return numerical.var()
thyroid_data=calculate_thyroid_data("Lab Session Data.xlsx")
datatype=attribute_datatype(thyroid_data)
categorical=categorical_attributes(thyroid_data)
numerical=numerical_attributes(thyroid_data)
range_data=data_range(thyroid_data)
missing=missing_values(thyroid_data)
outlier=outliers(thyroid_data)
mean=mean_value(thyroid_data)
variance=variance_value(thyroid_data)
print("Data Types")
print(datatype)
print()
print("Categorical Attributes")
print(categorical)
print()
print("Encoding Scheme")
for column in categorical:
    print(column,": One-Hot Encoding")
print()
print("Numerical Attributes")
print(numerical)
print()
print("Data Range")
print(range_data)
print()
print("Missing Values")
print(missing)
print()
print("Outliers")
print(outlier)
print()
print("Mean")
print(mean)
print()
print("Variance")
print(variance)

Data Types
Record ID                     int64
age                           int64
sex                          object
on thyroxine                 object
query on thyroxine           object
on antithyroid medication    object
sick                         object
pregnant                     object
thyroid surgery              object
I131 treatment               object
query hypothyroid            object
query hyperthyroid           object
lithium                      object
goitre                       object
tumor                        object
hypopituitary                object
psych                        object
TSH measured                 object
TSH                          object
T3 measured                  object
T3                           object
TT4 measured                 object
TT4                          object
T4U measured                 object
T4U                          object
FTI measured                 object
FTI                          object
TBG measured     

In [21]:
import pandas as pd
def calculate_thyroid_data(file_name):
    dataframe=pd.read_excel(file_name,sheet_name="thyroid0387_UCI")
    return dataframe
def binary_columns(dataframe):
    columns=[]
    for column in dataframe.columns:
        if dataframe[column].dropna().nunique()==2:
            columns.append(column)
    return columns
def similarity_measure(dataframe):
    binary=binary_columns(dataframe)
    vector1=dataframe.loc[0,binary]
    vector2=dataframe.loc[1,binary]
    f11=((vector1==1)&(vector2==1)).sum()
    f10=((vector1==1)&(vector2==0)).sum()
    f01=((vector1==0)&(vector2==1)).sum()
    f00=((vector1==0)&(vector2==0)).sum()
    jc=f11/(f11+f10+f01)
    smc=(f11+f00)/(f11+f10+f01+f00)
    return f11,f10,f01,f00,jc,smc
thyroid_data=calculate_thyroid_data("Lab Session Data.xlsx")
f11,f10,f01,f00,jc,smc=similarity_measure(thyroid_data)
print("f11 :",f11)
print("f10 :",f10)
print("f01 :",f01)
print("f00 :",f00)
print("Jaccard Coefficient :",jc)
print("Simple Matching Coefficient :",smc)

f11 : 0
f10 : 0
f01 : 0
f00 : 0
Jaccard Coefficient : nan
Simple Matching Coefficient : nan


C:\Users\jaswa\AppData\Local\Temp\ipykernel_2700\3092564985.py:19: RuntimeWarning: invalid value encountered in scalar divide
  jc=f11/(f11+f10+f01)
C:\Users\jaswa\AppData\Local\Temp\ipykernel_2700\3092564985.py:20: RuntimeWarning: invalid value encountered in scalar divide
  smc=(f11+f00)/(f11+f10+f01+f00)


In [23]:
import pandas as pd
import numpy as np
def calculate_thyroid_data(file_name):
    dataframe=pd.read_excel(file_name,sheet_name="thyroid0387_UCI")
    return dataframe
def cosine_similarity(dataframe):
    dataframe=dataframe.fillna(0)
    for column in dataframe.columns:
        if dataframe[column].dtype=="object":
            dataframe[column]=pd.factorize(dataframe[column])[0]
    vector1=dataframe.iloc[0].to_numpy(dtype=float)
    vector2=dataframe.iloc[1].to_numpy(dtype=float)
    dot_product=np.dot(vector1,vector2)
    magnitude1=np.linalg.norm(vector1)
    magnitude2=np.linalg.norm(vector2)
    cosine=dot_product/(magnitude1*magnitude2)
    return dot_product,magnitude1,magnitude2,cosine
thyroid_data=calculate_thyroid_data("Lab Session Data.xlsx")
dot_product,magnitude1,magnitude2,cosine=cosine_similarity(thyroid_data)
print("Dot Product :",dot_product)
print("Magnitude of Vector 1 :",magnitude1)
print("Magnitude of Vector 2 :",magnitude2)
print("Cosine Similarity :",cosine)

Dot Product : 7.069463443026281e+17
Magnitude of Vector 1 : 840801013.0000006
Magnitude of Vector 2 : 840801014.0000006
Cosine Similarity : 0.9999999999999998


In [27]:
import pandas as pd
import numpy as np
def calculate_thyroid_data(file_name):
    dataframe=pd.read_excel(file_name,sheet_name="thyroid0387_UCI")
    return dataframe
def check_outliers(column):
    Q1=column.quantile(0.25)
    Q3=column.quantile(0.75)
    IQR=Q3-Q1
    lower=Q1-1.5*IQR
    upper=Q3+1.5*IQR
    return ((column<lower)|(column>upper)).any()
def data_imputation(dataframe):
    dataframe=dataframe.replace("?",np.nan)
    for column in dataframe.columns:
        if pd.api.types.is_numeric_dtype(dataframe[column]):
            if check_outliers(dataframe[column].dropna()):
                dataframe[column]=dataframe[column].fillna(dataframe[column].median())
            else:
                dataframe[column]=dataframe[column].fillna(dataframe[column].mean())
        else:
            dataframe[column]=dataframe[column].fillna(dataframe[column].mode()[0])
    return dataframe
thyroid_data=calculate_thyroid_data("Lab Session Data.xlsx")
imputed_data=data_imputation(thyroid_data)
print(imputed_data.isnull().sum())
print()
print(imputed_data.head())

C:\Users\jaswa\AppData\Local\Temp\ipykernel_2700\2492613462.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataframe=dataframe.replace("?",np.nan)


Record ID                    0
age                          0
sex                          0
on thyroxine                 0
query on thyroxine           0
on antithyroid medication    0
sick                         0
pregnant                     0
thyroid surgery              0
I131 treatment               0
query hypothyroid            0
query hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
hypopituitary                0
psych                        0
TSH measured                 0
TSH                          0
T3 measured                  0
T3                           0
TT4 measured                 0
TT4                          0
T4U measured                 0
T4U                          0
FTI measured                 0
FTI                          0
TBG measured                 0
TBG                          0
referral source              0
Condition                    0
dtype: int64

   Record ID  age sex on 

In [29]:
import pandas as pd
import numpy as np
def calculate_thyroid_data(file_name):
    dataframe=pd.read_excel(file_name,sheet_name="thyroid0387_UCI")
    return dataframe
def normalize_data(dataframe):
    normalized_data=dataframe.copy()
    numerical_columns=normalized_data.select_dtypes(include=[np.number]).columns
    for column in numerical_columns:
        minimum=normalized_data[column].min()
        maximum=normalized_data[column].max()
        if maximum!=minimum:
            normalized_data[column]=(normalized_data[column]-minimum)/(maximum-minimum)
    return normalized_data
thyroid_data=calculate_thyroid_data("Lab Session Data.xlsx")
normalized_data=normalize_data(thyroid_data)
print("Normalized Dataset")
print(normalized_data.head())

Normalized Dataset
      Record ID       age sex on thyroxine query on thyroxine  \
0  0.000000e+00  0.000427   F            f                  f   
1  3.410871e-08  0.000427   F            f                  f   
2  9.891527e-07  0.000610   F            f                  f   
3  6.934301e-05  0.000534   F            f                  f   
4  6.937712e-05  0.000473   F            f                  f   

  on antithyroid medication sick pregnant thyroid surgery I131 treatment  ...  \
0                         f    f        f               f              f  ...   
1                         f    f        f               f              f  ...   
2                         f    f        f               f              f  ...   
3                         f    f        f               f              f  ...   
4                         f    f        f               f              f  ...   

  TT4 measured  TT4 T4U measured T4U FTI measured FTI TBG measured TBG  \
0            f    ?          

In [1]:
import os
print(os.getcwd())

C:\Users\jaswa\Machine Learning


In [3]:
import os

print("Current directory:", os.getcwd())
print("Files in current directory:")
print(os.listdir())

Current directory: C:\Users\jaswa\Machine Learning
Files in current directory:
['.ipynb_checkpoints', 'Lab Session Data.xlsx', 'Lab1.ipynb', 'Lab2.ipynb']
